PREFIX TI: <http://example.org/threatintelligence/>
PREFIX RDF: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX RDFS: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?osLabelAPT
WHERE { 
    ?APTdataset RDF:type TI:Dataset ;
              RDFS:label "APT" .
    ?osAPT TI:fromDataset ?APTdataset .
    ?osAPT TI:hasOSlabel ?osLabelAPT .
    FILTER NOT EXISTS {
        ?NCSCdataset RDF:type TI:Dataset ;
                  RDFS:label "NCSC" .
        ?osNCSC TI:fromDataset ?NCSCdataset .
        ?osNCSC TI:hasOSlabel ?osLabelAPT .
    }
}