PREFIX TI: <http://example.org/threatintelligence/>
PREFIX RDF: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX RDFS: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?product (COUNT(DISTINCT ?vulnerability) AS ?count)
WHERE {
  ?vulnerability RDF:type TI:Vulnerability .
  ?vulnerability TI:affectsProduct ?product .
  ?vulnerability TI:hasDescriptionChange ?justification .
  ?justification RDFS:label ?label .

  FILTER(?label IN ("Unjustified", "Unimportant"))
}
GROUP BY ?product
ORDER BY DESC(?count)
LIMIT 5