PREFIX TI: <http://example.org/threatintelligence/>
PREFIX RDF: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX RDFS: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT(*) AS ?totalVulnerabilities)
WHERE {
  {
    SELECT ?vulnerability
    WHERE {
      ?vulnerability RDF:type TI:Vulnerability .
            
      ?vulnerability TI:hasLikelihood ?likelihood .
      ?likelihood RDFS:label ?likelihoodLabel .
    }
    GROUP BY ?vulnerability
    HAVING (COUNT(DISTINCT ?likelihoodLabel) > 1)
  }
}